### PR TITLE
Include nginx config in dockerfile

### PR DESCRIPTION
**Pull request by code28**
This is a rather rough suggestion, so I put this into another PR:
I'm a huge fan of as few files as possible and very simple `Dockerfile`s, that's why I included a simple nginx config inside the `Dockerfile`. This config is slightly different from the nginx default one, because it redirects every request to `index.html`.

### CODE REVIEW

**Comment by joscdk** [comment]
@code28 hmm are you sure that works properly with VueJS. The reason for the other nginx file, is it's compatible with VueRouter, so in SPA you can still refresh the site and stay on the same page.

**Comment by code28** [comment]
I actually didn't change anything semantically, so if the other one worked, this one should work as well. It's just the "old" file (without newlines and whitespace) compressed into one line. Or did I miss something?

**Comment by code28** [comment]
(Rebased onto the new master branch and added IPv6)

**Comment by joscdk** [comment]
Oh perfect, didn't spot that, very nice work :+1:

**Pull request merged**
